### ISSUE TITLE
Error in CheckM stage

### ISSUE THREAD

**Issue by prehensilecode** [edgraham/BinSanity#29]
Binsanity-lc v0.2.7
Python 2.7.13 (Intel Distribution for Python)

Commandline:

     Binsanity-lc -f. -l ${DATADIR}/contig.fa -c ${DATADIR}/COVERAGE.cov -o ${OUTDIR} --threads 20

Two errors occured during the run (full output attached as txt file):

```
          Cluster 50:Traceback (most recent call last):
  File "/home/juser/.local/bin/checkm", line 36, in <module>
    from checkm import main
  File "/home/juser/.local/lib/python2.7/site-packages/checkm/main.py", line 25, in <module>
    from checkm.defaultValues import DefaultValues
  File "/home/juser/.local/lib/python2.7/site-packages/checkm/defaultValues.py", line 26, in <module>
    class DefaultValues():
  File "/home/juser/.local/lib/python2.7/site-packages/checkm/defaultValues.py", line 29, in DefaultValues
    __DBM = DBManager()
  File "/home/juser/.local/lib/python2.7/site-packages/checkm/checkmData.py", line 114, in __init__
    if not self.setRoot():
  File "/home/juser/.local/lib/python2.7/site-packages/checkm/checkmData.py", line 140, in setRoot
    path = self.confirmPath(path=path)
  File "/home/juser/.local/lib/python2.7/site-packages/checkm/checkmData.py", line 162, in confirmPath
    path = raw_input("Where should CheckM store it's data?\n" \
EOFError: EOF when reading a line
 17
```
and 

```
  File "/home/juser/.local/bin/Binsanity-lc", line 498, in <module>
    checkm_analysis(str(args.prefix)+"-checkm_lineagewf-binsanity.out",".fna",str(out_1),args.prefix)
  File "/home/juser/.local/bin/Binsanity-lc", line 302, in checkm_analysis
    del new_2[0]
IndexError: list assignment index out of range
```
In the file `BinSanityLC-checkm_lineagewf-binsanity.out` there is the following error message:

```

    It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
    Where should CheckM store it's data?
    Please specify a location or type 'abort' to stop trying: 
```

[binsanitylc_output.txt](https://github.com/edgraham/BinSanity/files/2695655/binsanitylc_output.txt)

**Comment by edgraham** [comment]
Hello,

This looks like it is an issue with the checkM installation in your system
path. I believe you have not set the location of the checkM data files.
Please see their installation  page here
<https://github.com/Ecogenomics/CheckM/wiki/Installation>. Take a look at
the section I have referenced below as I believe thats where the error
is coming from.

`CheckM relies on a number of precalculated data files which can be
downloaded from https://data.ace.uq.edu.au/public/CheckM_databases/.
Decompress the file to an appropriate folder and run checkm data setRoot to
inform CheckM of where the files have been placed.`

Please let me know if this fixes the issue!

-Elaina

**Comment by prehensilecode** [comment]
Thanks, that fixed it.
