### ISSUE TITLE
BinSanity docker run-error in "_continuous_distns.py"

### ISSUE THREAD

**Issue by Jigyasa3** [edgraham/BinSanity#40]
I am running BinSanity on docker, but I am getting the following error which seems to be a bug in the docker image.

I have already changed my ./local file which contains my python modules so that it doesn't interfere with docker.

My code-
$module load singularity/3.0.3
$singularity pull docker://shengwei/binsanity:latest #pulling the latest version on BinSanity
$singularity exec binsanity_latest.sif Binsanity-lc -h #checking if it runs

Error-
Traceback (most recent call last):
  File "/opt/conda/bin/Binsanity-lc", line 7, in <module>
    from sklearn.cluster import AffinityPropagation
  File "/opt/conda/lib/python2.7/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering
  File "/opt/conda/lib/python2.7/site-packages/sklearn/cluster/spectral.py", line 15, in <module>
    from ..metrics.pairwise import pairwise_kernels
  File "/opt/conda/lib/python2.7/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
    from .ranking import auc
  File "/opt/conda/lib/python2.7/site-packages/sklearn/metrics/ranking.py", line 27, in <module>
    from scipy.stats import rankdata
  File "/opt/conda/lib/python2.7/site-packages/scipy/stats/__init__.py", line 367, in <module>
    from .stats import *
  File "/opt/conda/lib/python2.7/site-packages/scipy/stats/stats.py", line 173, in <module>
    from . import distributions
  File "/opt/conda/lib/python2.7/site-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/opt/conda/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py", line 3345
SyntaxError: Non-ASCII character '\xe2' in file /opt/conda/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py on line 3346, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by edgraham** [comment]
Hello,

Thanks for this comment. I am working on updating the docker image so it works properly. There seems to have been some issues with both the docker and conda installs. 

-Elaina
