### ISSUE TITLE
Error during BinSanity execution prevent correct outputs from beign created

### ISSUE THREAD

**Issue by apcamargo** [edgraham/BinSanity#45]
I'm testing BinSanity with the provided test data. However, my results directory seems to be different from what would be expected. Those are the files/directories in my results folder:

```
BINSANITY-INITIAL
BinSanityWf_binsanity_checkm
BinSanityWf_checkm_lineagewf-results.txt
BinSanityWf.checkm.logfile
BinSanityWf.log
```

I also inspected the `BinSanityWf.log` file and noticed that an error had occured during the execution:

```
(...)
Finished parsing hits for 33 of 33 (100.00%) bins.
Traceback (most recent call last):
  File "/home/antoniop.camargo/anaconda3/envs/binning/bin/Binsanity-wf", line 460, in <module>
    args.prefix)+"_checkm_lineagewf-results.txt"), ".fna", str(out_1), args.prefix)
  File "/home/antoniop.camargo/anaconda3/envs/binning/bin/Binsanity-wf", line 274, in checkm_analysis
    highRedundancy = np.setdiff1d(all, (highCompletion+lowCompletion++strainRedundancy))
TypeError: bad operand type for unary +: 'list'

        ******************************************************
        **********************BinSanity***********************
        |____________________________________________________|
        |                                                    |
        |             Computing Coverage Array               |
        |____________________________________________________|
        
          Preference: -3
          Maximum Iterations: 4000
          Convergence Iterations: 400
          Contig Cut-Off: 1000
          Damping Factor: 0.95
          Coverage File: Infant_gut_assembly.cov.x100.lognorm
          Fasta File: igm.fa
          Output Directory: IGM-BinsanityWF
          (4189, 11)

         ______________________________________________________
        |                                                      |
        |                 Clustering Contigs                   |
        |______________________________________________________|

        
          Cluster 0: 4
          Cluster 18: 15
          Cluster 33: 22
          Cluster 2: 25
          Cluster 1: 11
          Cluster 3: 3
          Cluster 4: 7
          Cluster 5: 24
          Cluster 39: 25
          Cluster 29: 20
          Cluster 31: 23
          Cluster 7: 19
          Cluster 6: 17
          Cluster 8: 332
          Cluster 9: 294
          Cluster 22: 7
          Cluster 10: 18
          Cluster 19: 208
          Cluster 11: 256
          Cluster 12: 570
          Cluster 21: 71
          Cluster 15: 258
          Cluster 13: 3
          Cluster 14: 4
          Cluster 16: 413
          Cluster 17: 504
          Cluster 20: 158
          Cluster 23: 494
          Cluster 25: 71
          Cluster 24: 4
          Cluster 26: 63
          Cluster 30: 16
          Cluster 27: 34
          Cluster 28: 1
          Cluster 32: 20
          Cluster 34: 19
          Cluster 35: 43
          Cluster 36: 24
          Cluster 37: 3
          Cluster 38: 86
          Total Number of Bins: 33

         *|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*
         _____________________________________________________
         _____________________________________________________
        |                                                     |
        |                   Creating Bins                     |
        |_____________________________________________________|
        

         _____________________________________________________

                       Putative Bins Computed
                       in 1276.9271821975708 seconds
         _____________________________________________________

         _____________________________________________________
        |                                                     |
        |       Evaluating Genome With CheckM Lineage_wf      |
        |_____________________________________________________|
```

**Comment by edgraham** [comment]
Hello,

I am glad you caught this, it is repaired in the newest version so that this shouldn't happen again.  Please let me know if you run into any further issues.

-Elaina

**Comment by apcamargo** [comment]
Thanks @edgraham!

Would it be possible to upload the source to PyPI too? This is needed to update the Conda recipe

**Comment by edgraham** [comment]
I think you just need to wait for it to update in conda. The source is on
PyPI. It wasn't until I updated today (apparently the default twine command
I was using only uploaded the wheel).
