### ISSUE TITLE
Test works but binsanity-profile fails

### ISSUE THREAD

**Issue by biotemon** [edgraham/BinSanity#59]
` Binsanity-profile -i contigs_v2.fa -s /Volumes/Red_4TB/scratch_BK/CS_BACKUP/p31_anvio_metagenomes/OC26_EXPERIMENT/binsanity_bins/bam_files/ -c binsanity.profile`

```
/Users/tito_miniconda/opt/miniconda3/bin/Binsanity-profile:152: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if args.outDirectory is not ".":

        ******************************************************
                    Contigs formated to generate counts
        ******************************************************
        
Traceback (most recent call last):
  File "/Users/tito_miniconda/opt/miniconda3/bin/Binsanity-profile", line 164, in <module>
    feature_counts(args.inputMapLoc, args.outDirectory, args.Threads)
  File "/Users/tito_miniconda/opt/miniconda3/bin/Binsanity-profile", line 31, in feature_counts
    subprocess.call(["featureCounts", "-M", "-O", "-F", "SAF", "-T", str(threads), "-a", os.path.join(outputdir, str(
  File "/Users/tito_miniconda/opt/miniconda3/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/tito_miniconda/opt/miniconda3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/tito_miniconda/opt/miniconda3/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'featureCounts'
```

**Comment by edgraham** [comment]
Hello Tito,

I'm sorry you're having issues. This looks like a python related syntax
error. I'll look into it ASAP and send out a repair. In the meantime try
these things:

1. Try running the test dataset and see if that will run.
2.  Try dropping your conda env to python 3.6 and re-running this command.


-Elaina

**Comment by saras224** [comment]
Hi @edgraham 
I also got an error while running binsanity_profile command. 
Command: Binsanity-profile -i A1.fa -s /home/saraswati/MAPPED_SORTED/SORTED/BINSANITY_TRIAL/ -c binsanity_coverage

error message:
/lustre/saraswati/anaconda3/bin/Binsanity-profile:152: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if args.outDirectory is not ".":

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.3

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           A1.sorted.bam                                    ||
||                                                                            ||
||             Output file : A1.sorted.bam.readcounts                         ||
||                 Summary : A1.sorted.bam.readcounts.summary                 ||
||              Paired-end : no                                               ||
||        Count read pairs : no                                               ||
||              Annotation : A1.sorted.bam.saf (SAF)                          ||
||      Dir for temp files : .                                                ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : counted                                          ||
|| Multi-overlapping reads : counted                                          ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file A1.sorted.bam.saf ...                                 ||
||    Features : 35630                                                        ||
||    Meta-features : 35630                                                   ||
||    Chromosomes/contigs : 35630                                             ||
||                                                                            ||
|| Process BAM file A1.sorted.bam...                                          ||
ERROR: Paired-end reads were detected in single-end read library : /home/saraswati/MAPPED_SORTED/SORTED/BINSANITY_TRIAL/A1.sorted.bam

        ******************************************************
                    Contigs formated to generate counts
        ******************************************************
        
Traceback (most recent call last):
  File "/lustre/saraswati/anaconda3/bin/Binsanity-profile", line 166, in <module>
    make_coverage(args.inputFasta, args.outCov, args.outDirectory)
  File "/lustre/saraswati/anaconda3/bin/Binsanity-profile", line 54, in make_coverage
    contig_length = cov_data[k].pop(0)
IndexError: pop from empty list

real	1m37.531s
user	0m54.310s
sys	0m1.387s

Kindly help me resolve the error!

Thanks in Advance!
